# Data Preprocessing Menggunakan Scikit-Learn

## **Sampel Data**

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data=np.array([[2.1,-1.9,5.5],
                      [-1.5,2.4,3.5],
                      [0.5,-7.9,5.6],
                      [5.9,2.3,-5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [2]:
sample_data.shape

(4, 3)

## **Binarisation**

In [3]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [24]:
# Setiap nilai yang lebih kecil dari 0.5 akan dikonversikan menjadi nilai 0 dan diatas 0.5 akan dikonversikan menjadi 1 dan nilai yang persis dengan thereshold akan dikonversikan menjadi nilai 0.
preprocessor=preprocessing.Binarizer(threshold=0.5)
binarised_data=preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

## **Scalling**

In [10]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [25]:
# membuat Scaling pada angka tertentu antara 0-1.nilai 0 mengindikasikan nilai terkecil dan 1 mengindikasikan nilai terbesar dari data.
processor=preprocessing.MinMaxScaler(feature_range=(0,1))
processor.fit(sample_data)
Scaled_Data=processor.transform(sample_data)
Scaled_Data# diperhatikan ber kolomnya...scallingnya per kolom.

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [14]:
Scaled_Data=processor.fit_transform(sample_data)
Scaled_Data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

## L1 Normalization:Least Absolut Deviation

In [15]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [21]:
l1_normalised_data=preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

## L2 Normalization:Least Square

In [22]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [23]:
l2_normalised_data=preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])